#!/usr/bin/env node

/**
 * Download bookmaker logos from Logo.dev API and cache locally
 * Usage: node scripts/download-logos.js
 */

const https = require('https');
const fs = require('fs');
const path = require('path');

const BOOKMAKER_DOMAINS = {
  'Pinnacle': 'pinnacle.com',
  'Betfair_EU': 'betfair.com',
  'Draftkings': 'draftkings.com',
  'Fanduel': 'fanduel.com',
  'Betfair_AU': 'betfair.com.au',
  'Betfair_UK': 'betfair.co.uk',
  'Betmgm': 'betmgm.com',
  'Betrivers': 'betrivers.com',
  'Betsson': 'betsson.com',
  'Marathonbet': 'marathonbet.com',
  'Lowvig': 'lowvig.com',
  'Nordicbet': 'nordicbet.com',
  'Mybookie': 'mybookie.ag',
  'Betonline': 'betonline.ag',
  'Bovada': 'bovada.lv',
  'Sportsbet': 'sportsbet.com.au',
  'Pointsbet': 'pointsbet.com',
  'Tab': 'tab.com.au',
  'Tabtouch': 'tab.com.au',
  'Unibet_AU': 'unibet.com.au',
  'Ladbrokes_AU': 'ladbrokes.com.au',
  'Neds': 'neds.com.au',
  'Betr': 'betr.com.au',
  'Boombet': 'boombet.com.au',
  'Williamhill_US': 'williamhill.us',
  'Sbk': 'sbk.com',
  'Fanatics': 'fanatics.com',
  'Ballybet': 'ballybet.com',
  'Betparx': 'betparx.com',
  'Espnbet': 'espnbet.com',
  'Fliff': 'fliff.com',
  'Hardrockbet': 'hardrockbet.com',
  'Rebet': 'rebet.com',
  'Williamhill_UK': 'williamhill.co.uk',
  'Betvictor': 'betvictor.com',
  'Coral': 'coral.co.uk',
  'Skybet': 'skybet.com',
  'Paddypower': 'paddypower.com',
  'Boylesports': 'boylesports.com',
  'Betfred': 'betfred.com',
  'Bwin': 'bwin.com',
  'Williamhill_EU': 'williamhill.eu',
  'Codere': 'codere.com',
  'Tipico': 'tipico.com',
  'Leovegas': 'leovegas.com',
  'Parionssport': 'parionssport.fr',
  'Winamax_FR': 'winamax.fr',
  'Winamax_DE': 'winamax.de',
  'Unibet_FR': 'unibet.fr',
  'Unibet_NL': 'unibet.nl',
  'Unibet_SE': 'unibet.se',
  'Betclic': 'betclic.com',
};

const LOGO_DIR = path.join(__dirname, '../frontend/public/logos/bookmakers');
const OUTPUT_FILE = path.join(__dirname, '../frontend/src/utils/bookmakerLogosLocal.js');

// Ensure logo directory exists
if (!fs.existsSync(LOGO_DIR)) {
  fs.mkdirSync(LOGO_DIR, { recursive: true });
}

let downloaded = 0;
let failed = 0;
const logoMap = {};

const downloadLogo = (bookmakerName, domain, callback) => {
  const filename = bookmakerName.toLowerCase().replace(/_/g, '-');
  const filepath = path.join(LOGO_DIR, `${filename}.png`);
  
  // Skip if already exists
  if (fs.existsSync(filepath)) {
    console.log(`✓ Skipping ${bookmakerName} (already cached)`);
    logoMap[bookmakerName] = `/logos/bookmakers/${filename}.png`;
    callback();
    return;
  }

  const url = `https://img.logo.dev/${domain}?format=png&size=96&theme=light&retina=true`;
  
  https.get(url, (response) => {
    if (response.statusCode !== 200) {
      console.log(`⊘ Skipping ${bookmakerName} (status ${response.statusCode} - will use fallback SVG)`);
      // Don't add to logoMap - will use fallback SVG
      failed++;
      callback();
      return;
    }

    const file = fs.createWriteStream(filepath);
    response.pipe(file);
    
    file.on('finish', () => {
      file.close();
      console.log(`✓ Downloaded ${bookmakerName}`);
      logoMap[bookmakerName] = `/logos/bookmakers/${filename}.png`;
      downloaded++;
      callback();
    });

    file.on('error', (err) => {
      fs.unlink(filepath, () => {});
      console.log(`⊘ Error downloading ${bookmakerName}: ${err.message} (will use fallback SVG)`);
      failed++;
      callback();
    });
  }).on('error', (err) => {
    console.log(`⊘ Error downloading ${bookmakerName}: ${err.message} (will use fallback SVG)`);
    failed++;
    callback();
  });
};

// Download all logos sequentially (100ms delay)
const bookmakers = Object.entries(BOOKMAKER_DOMAINS);
let index = 0;

const downloadNext = () => {
  if (index >= bookmakers.length) {
    // Generate JS file
    generateJSFile();
    return;
  }

  const [bookmakerName, domain] = bookmakers[index];
  index++;

  downloadLogo(bookmakerName, domain, () => {
    setTimeout(downloadNext, 100); // Rate limiting
  });
};

const generateJSFile = () => {
  const content = `/**
 * Local cached bookmaker logos
 * Auto-generated by scripts/download-logos.js
 * 
 * Maps bookmaker names to local PNG files in public/logos/bookmakers/
 */

export const BOOKMAKER_LOGOS_LOCAL = ${JSON.stringify(logoMap, null, 2)};

/**
 * Get local logo path for a bookmaker
 * @param {string} bookmakerName - Name of the bookmaker
 * @returns {string|null} - Local path to logo or null if not cached
 */
export const getBookmakerLogoLocal = (bookmakerName) => {
  return BOOKMAKER_LOGOS_LOCAL[bookmakerName] || null;
};
`;

  fs.writeFileSync(OUTPUT_FILE, content, 'utf-8');
  
  console.log(`\n✅ Complete!`);
  console.log(`   Downloaded: ${downloaded}`);
  console.log(`   Failed: ${failed}`);
  console.log(`   Output: ${OUTPUT_FILE}`);
};

console.log('📥 Downloading bookmaker logos from Logo.dev...\n');
downloadNext();
