#!/usr/bin/env node

/**
 * Fetch Bookmaker Logos from Logo.dev API
 * 
 * Usage: node scripts/fetch-logos.js
 * 
 * This script:
 * 1. Fetches logos for all 52 bookmakers from Logo.dev API
 * 2. Saves them to public/logos/bookmakers/
 * 3. Updates frontend/src/utils/bookmakerLogos.js with local paths
 * 
 * Requires: Node.js 14+, fetch API (or node-fetch for older versions)
 */

const fs = require('fs');
const path = require('path');
const https = require('https');

// Bookmaker list (from pipeline_v2/ratings.py)
const BOOKMAKERS = {
  // 4⭐
  'Pinnacle': 'pinnacle',
  'Betfair_EU': 'betfair',
  'Draftkings': 'draftkings',
  'Fanduel': 'fanduel',
  
  // 3⭐
  'Betfair_AU': 'betfair',
  'Betfair_UK': 'betfair',
  'Betmgm': 'betmgm',
  'Betrivers': 'betrivers',
  'Betsson': 'betsson',
  'Marathonbet': 'marathonbet',
  'Lowvig': 'lowvig',
  
  // 2⭐
  'Nordicbet': 'nordicbet',
  'Mybookie': 'mybookie',
  'Betonline': 'betonline',
  'Bovada': 'bovada',
  
  // 1⭐ - AU
  'Sportsbet': 'sportsbet',
  'Pointsbet': 'pointsbet',
  'Tab': 'tab',
  'Tabtouch': 'tabtouch',
  'Unibet_AU': 'unibet',
  'Ladbrokes_AU': 'ladbrokes',
  'Neds': 'neds',
  'Betr': 'betr',
  'Boombet': 'boombet',
  
  // 1⭐ - US
  'Williamhill_US': 'williamhill',
  'Sbk': 'sbk',
  'Fanatics': 'fanatics',
  'Ballybet': 'ballybet',
  'Betparx': 'betparx',
  'Espnbet': 'espnbet',
  'Fliff': 'fliff',
  'Hardrockbet': 'hardrockbet',
  'Rebet': 'rebet',
  
  // 1⭐ - UK
  'Williamhill_UK': 'williamhill',
  'Betvictor': 'betvictor',
  'Coral': 'coral',
  'Skybet': 'skybet',
  'Paddypower': 'paddypower',
  'Boylesports': 'boylesports',
  'Betfred': 'betfred',
  
  // 1⭐ - EU
  'Bwin': 'bwin',
  'Williamhill_EU': 'williamhill',
  'Codere': 'codere',
  'Tipico': 'tipico',
  'Leovegas': 'leovegas',
  'Parionssport': 'parionssport',
  'Winamax_FR': 'winamax',
  'Winamax_DE': 'winamax',
  'Unibet_FR': 'unibet',
  'Unibet_NL': 'unibet',
  'Unibet_SE': 'unibet',
  'Betclic': 'betclic',
};

const LOGO_DIR = path.join(__dirname, '..', 'public', 'logos', 'bookmakers');
const OUTPUT_JS = path.join(__dirname, '..', 'frontend', 'src', 'utils', 'bookmakerLogos.js');

// Create directory if it doesn't exist
function ensureDir(dir) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
    console.log(`✓ Created directory: ${dir}`);
  }
}

// Download file from URL
function downloadFile(url, filePath) {
  return new Promise((resolve, reject) => {
    const file = fs.createWriteStream(filePath);
    https.get(url, (response) => {
      if (response.statusCode !== 200) {
        file.destroy();
        reject(new Error(`HTTP ${response.statusCode}: ${url}`));
        return;
      }
      response.pipe(file);
      file.on('finish', () => {
        file.close();
        resolve();
      });
    }).on('error', (err) => {
      fs.unlink(filePath, () => {}); // Delete file on error
      reject(err);
    });
  });
}

// Fetch all logos
async function fetchAllLogos() {
  console.log(`\n📥 Fetching ${Object.keys(BOOKMAKERS).length} bookmaker logos...\n`);
  
  ensureDir(LOGO_DIR);
  
  const results = {};
  const failures = [];
  let count = 0;
  
  for (const [bookmakerName, logoName] of Object.entries(BOOKMAKERS)) {
    const url = `https://api.logo.dev/logo?company=${logoName}&format=svg`;
    const fileName = `${bookmakerName.toLowerCase()}.svg`;
    const filePath = path.join(LOGO_DIR, fileName);
    
    try {
      await downloadFile(url, filePath);
      results[bookmakerName] = `/logos/bookmakers/${fileName}`;
      console.log(`✓ ${bookmakerName.padEnd(20)} → ${fileName}`);
      count++;
    } catch (err) {
      failures.push({ bookmakerName, error: err.message });
      results[bookmakerName] = null; // Will use fallback
      console.log(`✗ ${bookmakerName.padEnd(20)} → Failed: ${err.message}`);
    }
    
    // Rate limit: 100ms between requests
    await new Promise(resolve => setTimeout(resolve, 100));
  }
  
  console.log(`\n✓ Downloaded ${count}/${Object.keys(BOOKMAKERS).length} logos`);
  
  if (failures.length > 0) {
    console.log(`\n⚠️  ${failures.length} logos failed to download (will use fallbacks)`);
  }
  
  return results;
}

// Generate updated bookmakerLogos.js
function generateJSFile(logoMap) {
  const entries = Object.entries(logoMap)
    .map(([name, path]) => {
      if (!path) {
        return `  '${name}': null, // Will use fallback`;
      }
      return `  '${name}': '${path}',`;
    })
    .join('\n');
  
  const content = `/**
 * Bookmaker logo mapping and utilities
 * Auto-generated by scripts/fetch-logos.js
 * 
 * Local paths to downloaded logos (SVG format)
 * Fallback to auto-generated initials if logo missing
 */

// Local logo paths
const BOOKMAKER_LOGOS = {
${entries}
};

/**
 * Get logo URL for a bookmaker
 * @param {string} bookmakerName - Name of the bookmaker
 * @returns {string} - Logo path or fallback
 */
export const getBookmakerLogo = (bookmakerName) => {
  if (!bookmakerName) return null;
  const localPath = BOOKMAKER_LOGOS[bookmakerName];
  return localPath || createFallbackLogo(bookmakerName);
};

/**
 * Create a fallback SVG logo (initials in colored box)
 * @param {string} bookmakerName - Name of the bookmaker
 * @returns {string} - Data URL for fallback logo
 */
const createFallbackLogo = (bookmakerName) => {
  const initials = bookmakerName
    .split(/[_\\s]+/)
    .map(word => word[0])
    .join('')
    .toUpperCase()
    .slice(0, 2);
  
  const colors = ['#4be1c1', '#3498db', '#f39c12', '#2ecc71', '#e74c3c'];
  const hash = bookmakerName.split('').reduce((acc, char) => acc + char.charCodeAt(0), 0);
  const bgColor = colors[hash % colors.length];
  
  const svg = \`
    <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 48 48">
      <rect width="48" height="48" rx="4" fill="\${bgColor}"/>
      <text x="24" y="30" font-size="18" font-weight="bold" fill="white" text-anchor="middle">
        \${initials}
      </text>
    </svg>
  \`;
  
  return \`data:image/svg+xml;base64,\${btoa(svg)}\`;
};

/**
 * Get bookmaker name display (removes underscores for region codes)
 * @param {string} bookmakerName - Raw bookmaker name
 * @returns {string} - Display name
 */
export const getBookmakerDisplayName = (bookmakerName) => {
  if (!bookmakerName) return '';
  return bookmakerName
    .replace(/_[A-Z]{2}$/, '')
    .replace(/_/g, ' ')
    .trim();
};

export default BOOKMAKER_LOGOS;
`;
  
  fs.writeFileSync(OUTPUT_JS, content, 'utf-8');
  console.log(`\n✓ Generated: ${OUTPUT_JS}`);
}

// Main execution
(async () => {
  try {
    console.log('🚀 Logo Fetcher - Downloading bookmaker logos\n');
    
    const logoMap = await fetchAllLogos();
    generateJSFile(logoMap);
    
    console.log('\n✅ Complete! Logos saved to:', LOGO_DIR);
    console.log('   Updated:', OUTPUT_JS);
    console.log('\n📝 Next steps:');
    console.log('   1. Commit the new logos: git add public/logos/');
    console.log('   2. Commit the updated mapping: git add frontend/src/utils/bookmakerLogos.js');
    console.log('   3. Push to GitHub and redeploy');
    
  } catch (error) {
    console.error('\n❌ Error:', error.message);
    process.exit(1);
  }
})();
