/**
 * Bookmaker logo mapping and utilities
 * Auto-generated by scripts/fetch-logos.js
 * 
 * Local paths to downloaded logos (SVG format)
 * Fallback to auto-generated initials if logo missing
 */

// Local logo paths
const BOOKMAKER_LOGOS = {
  'Pinnacle': null, // Will use fallback
  'Betfair_EU': null, // Will use fallback
  'Draftkings': null, // Will use fallback
  'Fanduel': null, // Will use fallback
  'Betfair_AU': null, // Will use fallback
  'Betfair_UK': null, // Will use fallback
  'Betmgm': null, // Will use fallback
  'Betrivers': null, // Will use fallback
  'Betsson': null, // Will use fallback
  'Marathonbet': null, // Will use fallback
  'Lowvig': null, // Will use fallback
  'Nordicbet': null, // Will use fallback
  'Mybookie': null, // Will use fallback
  'Betonline': null, // Will use fallback
  'Bovada': null, // Will use fallback
  'Sportsbet': null, // Will use fallback
  'Pointsbet': null, // Will use fallback
  'Tab': null, // Will use fallback
  'Tabtouch': null, // Will use fallback
  'Unibet_AU': null, // Will use fallback
  'Ladbrokes_AU': null, // Will use fallback
  'Neds': null, // Will use fallback
  'Betr': null, // Will use fallback
  'Boombet': null, // Will use fallback
  'Williamhill_US': null, // Will use fallback
  'Sbk': null, // Will use fallback
  'Fanatics': null, // Will use fallback
  'Ballybet': null, // Will use fallback
  'Betparx': null, // Will use fallback
  'Espnbet': null, // Will use fallback
  'Fliff': null, // Will use fallback
  'Hardrockbet': null, // Will use fallback
  'Rebet': null, // Will use fallback
  'Williamhill_UK': null, // Will use fallback
  'Betvictor': null, // Will use fallback
  'Coral': null, // Will use fallback
  'Skybet': null, // Will use fallback
  'Paddypower': null, // Will use fallback
  'Boylesports': null, // Will use fallback
  'Betfred': null, // Will use fallback
  'Bwin': null, // Will use fallback
  'Williamhill_EU': null, // Will use fallback
  'Codere': null, // Will use fallback
  'Tipico': null, // Will use fallback
  'Leovegas': null, // Will use fallback
  'Parionssport': null, // Will use fallback
  'Winamax_FR': null, // Will use fallback
  'Winamax_DE': null, // Will use fallback
  'Unibet_FR': null, // Will use fallback
  'Unibet_NL': null, // Will use fallback
  'Unibet_SE': null, // Will use fallback
  'Betclic': null, // Will use fallback
};

/**
 * Get logo URL for a bookmaker
 * @param {string} bookmakerName - Name of the bookmaker
 * @returns {string} - Logo path or fallback
 */
export const getBookmakerLogo = (bookmakerName) => {
  if (!bookmakerName) return null;
  const localPath = BOOKMAKER_LOGOS[bookmakerName];
  return localPath || createFallbackLogo(bookmakerName);
};

/**
 * Create a fallback SVG logo (initials in colored box)
 * @param {string} bookmakerName - Name of the bookmaker
 * @returns {string} - Data URL for fallback logo
 */
const createFallbackLogo = (bookmakerName) => {
  const initials = bookmakerName
    .split(/[_\s]+/)
    .map(word => word[0])
    .join('')
    .toUpperCase()
    .slice(0, 2);
  
  const colors = ['#4be1c1', '#3498db', '#f39c12', '#2ecc71', '#e74c3c'];
  const hash = bookmakerName.split('').reduce((acc, char) => acc + char.charCodeAt(0), 0);
  const bgColor = colors[hash % colors.length];
  
  const svg = `
    <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 48 48">
      <rect width="48" height="48" rx="4" fill="${bgColor}"/>
      <text x="24" y="30" font-size="18" font-weight="bold" fill="white" text-anchor="middle">
        ${initials}
      </text>
    </svg>
  `;
  
  return `data:image/svg+xml;base64,${btoa(svg)}`;
};

/**
 * Get bookmaker name display (removes underscores for region codes)
 * @param {string} bookmakerName - Raw bookmaker name
 * @returns {string} - Display name
 */
export const getBookmakerDisplayName = (bookmakerName) => {
  if (!bookmakerName) return '';
  return bookmakerName
    .replace(/_[A-Z]{2}$/, '')
    .replace(/_/g, ' ')
    .trim();
};

export default BOOKMAKER_LOGOS;
