/**
 * Local cached bookmaker logos
 * Auto-generated by scripts/download-logos.js
 * 
 * Maps bookmaker names to local PNG files in public/logos/bookmakers/
 */

export const BOOKMAKER_LOGOS_LOCAL = {};

/**
 * Get local logo path for a bookmaker
 * @param {string} bookmakerName - Name of the bookmaker
 * @returns {string|null} - Local path to logo or null if not cached
 */
export const getBookmakerLogoLocal = (bookmakerName) => {
  return BOOKMAKER_LOGOS_LOCAL[bookmakerName] || null;
};
